approve_by_comment: true
approve_regex: '^([Aa]pproved|:shipit:|:\+1:|I [Aa]pprove|LGTM)'
reject_regex: ^Rejected
reset_on_push: false
author_approval: ignored
reviewers:
  - name: core
    members:
      - keasler
      - trws
      - rhornung67
      - davidbeckingsale
      - DavidPoliakoff
      - jonesholger
    required: 1
  - name: everyone
    members:
      - ajkunen
      - trws
      - davidbeckingsale
      - DavidPoliakoff
      - keasler
      - rhornung67
      - jonesholger
      - willkill07
    required: 2
