find_package(CUDA)
  if(CUDA_FOUND)
    message(STATUS "CUDA found")
    set(RAJA_PLATFORM RAJA_PLATFORM_X86_SSE)
    set(RAJA_COMPILER RAJA_COMPILER_GNU)
    set(RAJA_USE_CUDA)
    set(CUDA_NVCC_FLAGS -O2; --expt-extended-lambda; -restrict; -arch compute_35; -std=c++11; -Xcompiler; -fopenmp)
    set (CUDA_PROPAGATE_HOST_FLAGS OFF)
    include_directories(${CUDA_INCLUDE_DIRS})
    #set(CMAKE_CXX_COMPILER nvcc)
    #set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2 --expt-extended-lambda -restrict -arch compute_35 -std=c++11 -Xcompiler -fopenmp")
  endif()
endif()
