#ifndef RAJA_forall_concepts_HPP
#define RAJA_forall_concepts_HPP

#include "RAJA/config.hpp"

#include "RAJA/pattern/detail/TypeTraits.hpp"
#include "RAJA/index/IndexSet.hpp"
#include "RAJA/index/RangeSegment.hpp"
#include "RAJA/policy/MultiPolicy.hpp"
#include "detail/TypeTraits.hpp"

namespace RAJA
{
// TODO: Several of these are based on camp type_traits, which themselves are
// automatically generated by camp's pseudo-concept interface.  We wish to
// simplify this chain of requirements, potentially moving the concepts
// themselves into camp

// The Range concept is derived from camp.  This concept is satisfied by any
// type with a begin() and end() iterator.
template<typename T>
concept Range = static_cast<bool>(type_traits::is_range<camp::decay<T>>::value);

// RandomAccessRange is also derived from camp, and is satisfied by any type
// with begin/end iterators and random access.
template<typename T>
concept RandomAccessRange = Range<T> && static_cast<bool>(
    type_traits::is_random_access_range<camp::decay<T>>::value);

template<typename T>
concept MultiPolicyConcept = static_cast<bool>(
    RAJA::type_traits::is_multi_policy<camp::decay<T>>::value);

template<typename T>
concept Integer =
    static_cast<bool>(type_traits::is_integral<camp::decay<T>>::value);

template<typename Pol>
concept ForallPolicy = RAJA::type_traits::is_policy_forall<Pol>();

template<typename T>
concept ForallParameterPack =
    RAJA::expt::type_traits::is_ForallParamPack<camp::decay<T>>::value;

}  // namespace RAJA

#endif
