#ifndef RAJA_forall_concepts_HPP
#define RAJA_forall_concepts_HPP

#include "RAJA/config.hpp"

#include "RAJA/pattern/detail/TypeTraits.hpp"
#include "RAJA/index/IndexSet.hpp"
#include "RAJA/index/RangeSegment.hpp"
#include "RAJA/policy/MultiPolicy.hpp"
#include "detail/TypeTraits.hpp"

namespace RAJA
{
// TODO: Several of these are based on camp type_traits, which themselves are
// automatically generated by camp's pseudo-concept interface.  We wish to
// simplify this chain of requirements, potentially moving the concepts
// themselves into camp

// The Range concept is derived from camp.  This concept is satisfied by any
// type with a begin() and end() iterator.
template<typename T>
concept Range = static_cast<bool>(type_traits::is_range<camp::decay<T>>::value);

// RandomAccessRange is also derived from camp, and is satisfied by any type
// with begin/end iterators and random access.
template<typename T>
concept RandomAccessRange = Range<T> && static_cast<bool>(
    type_traits::is_random_access_range<camp::decay<T>>::value);

template<typename T>
concept MultiPolicyConcept = static_cast<bool>(
    RAJA::type_traits::is_multi_policy<camp::decay<T>>::value);

template<typename T>
concept Integer =
    static_cast<bool>(type_traits::is_integral<camp::decay<T>>::value);

template<typename Pol>
concept ForallPolicy = RAJA::type_traits::is_policy_forall<Pol>();

template<typename T>
concept ForallParameterPack =
    RAJA::expt::type_traits::is_ForallParamPack<camp::decay<T>>::value;



// Concept for strongly typed index types.
template < typename T >
concept StrongIndexType = !std::integral<T> && requires (T val)
    {
      { stripIndexType(val) } -> std::integral;
    };

// Concept index types or strongly typed index types.
// TODO: improve the name
template < typename T >
concept IndexTypeConcept = std::integral<T> || StrongIndexType<T>;

// Concept for types that may be callable.
// Use std::invokable when the full set of arguments is known.
template < typename B >
concept PotentialInvokable =
    std::is_class_v<std::remove_cvref_t<B>> ||
    std::is_union_v<std::remove_cvref_t<B>> ||
    std::is_function_v<std::remove_cvref_t<B>> ||
    ( std::is_pointer_v<std::remove_cvref_t<B>> &&
      std::is_function_v<std::remove_cv_t<std::remove_pointer_t<std::remove_cvref_t<B>>>> );

consteval bool testPotentialInvokable() noexcept
{
  using I = int;
  using F = int();
  struct S{};
  union U{};
  using L = decltype([]{});
  static_assert(!PotentialInvokable<I>);
  static_assert(!PotentialInvokable<I&>);
  static_assert(!PotentialInvokable<I*>);
  static_assert(!PotentialInvokable<I[]>);
  static_assert(PotentialInvokable<F>);
  static_assert(PotentialInvokable<F&>);
  static_assert(PotentialInvokable<F*>);
  static_assert(PotentialInvokable<F*&>);
  static_assert(!PotentialInvokable<F**>);
  static_assert(!PotentialInvokable<F*[]>);
  static_assert(PotentialInvokable<S>);
  static_assert(PotentialInvokable<S&>);
  static_assert(!PotentialInvokable<S*>);
  static_assert(!PotentialInvokable<S[]>);
  static_assert(PotentialInvokable<U>);
  static_assert(PotentialInvokable<U&>);
  static_assert(!PotentialInvokable<U*>);
  static_assert(!PotentialInvokable<U[]>);
  static_assert(PotentialInvokable<L>);
  static_assert(PotentialInvokable<L&>);
  static_assert(!PotentialInvokable<L*>);
  static_assert(!PotentialInvokable<L[]>);
  return true;
}
static_assert(testPotentialInvokable());

// Concept for forall param objects.
template < typename Arg >
concept ForallParam = std::is_base_of_v<expt::detail::ForallParamBase, std::remove_cvref_t<Arg>>;

// Concept for forall arguments that may be forall param objects or callables.
template < typename Arg >
concept ForallParamsAndBody = ForallParam<Arg> || PotentialInvokable<Arg>;

}  // namespace RAJA

#endif
